### ISSUE TITLE
Formats not functioning properly

### ISSUE THREAD

**Issue by garryspins** [1ndiigo/Rockwall#2]
Luckperms is installed and configured, any reason why this is happening that could be on my end?
![img](https://i.imgur.com/vJPPim9.png)

**Comment by HoodieRocks** [comment]
Hi, make sure you have PlaceholderAPI installed and the player and luckperms placeholder expansion installed

**Comment by garryspins** [comment]
Installing PAPI, the player expansion and the luckperms extension seems to have fixed it.
Could you add this to the readme and descriptions of the plugin on plugin websites for noobies like me?

**Comment by HoodieRocks** [comment]
Sure!
